version: '3'
services: 
  db:
    image: postgres
    restart: always
    ports: 
      - '5432:5432'
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: rightman
  app-back:
    depends_on: 
      - db
    volumes: 
      - ./right-man-back:/usr/src/app
      - /usr/src/app/node_modules
    build: right-man-back
    ports:
      - '5000:5000'
    environment: 
      PORT: 5000
      NODE_ENV: development
      DATABASE_URL: postgres://username:password@db:5432/rightman